- OrrNyan/OrrNyan Watch App/Assets.xcassets/AccentColor.colorset/Contents.json
- OrrNyan/OrrNyan Watch App/Assets.xcassets/AppIcon.appiconset/Contents.json
- OrrNyan/OrrNyan Watch App/Assets.xcassets/Contents.json
- OrrNyan/OrrNyan Watch App/ContentView.swift
- OrrNyan/OrrNyan Watch App/OrrNyanApp.swift
- OrrNyan/OrrNyan Watch App/Preview Content/Preview Assets.xcassets/Contents.json
- OrrNyan/OrrNyan Watch App/StairTest.swift
- OrrNyan/OrrNyan.xcodeproj/project.pbxproj
- OrrNyan/OrrNyan.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- OrrNyan/OrrNyan.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- OrrNyan/OrrNyan/Assets.xcassets/AccentColor.colorset/Contents.json
- OrrNyan/OrrNyan/Assets.xcassets/AppIcon.appiconset/Contents.json
- OrrNyan/OrrNyan/Assets.xcassets/Contents.json
- OrrNyan/OrrNyan/ContentView.swift
- OrrNyan/OrrNyan/OrrNyanApp.swift
- OrrNyan/OrrNyan/Preview Content/Preview Assets.xcassets/Contents.json
- PR에 대한 설명
프로젝트 생성과 워치 층 데이터 테스트코드 추가
- projectinit
- 작업한 내용
프로젝트 생성과 워치 층 데이터 테스트코드 추가
> Projectinit

- OrrNyan/OrrNyan.xcodeproj/project.pbxproj
- OrrNyan/OrrNyan/Models/AppPush.swift
- OrrNyan/OrrNyan/Models/StageInfo.swift
- OrrNyan/OrrNyan/Models/User.swift
- OrrNyan/OrrNyan/Models/UserBadge.swift
- OrrNyan/OrrNyan/Models/UserFloor.swift
- OrrNyan/OrrNyan/Models/UserModel.swift
- OrrNyan/OrrNyan/Models/UserStage.swift
- PR에 대한 설명
모델 생성 작업
- chore/#10
- 작업한 내용
다음 모델들을 프로젝트에 생성함.
User, UserFloor, UserStage, UserBadge, AppPush, StageInfo
틀린 부분이 있다면 말씀해주세요.
또한, 모델은 변경사항이 발생할 수 있습니다. 여러분도 작업 하시다가 변경해야 할 것 같다면 언제든 말씀해주세요~
> [Chore] #10 - add Models

- OrrNyan/OrrNyan.xcodeproj/project.pbxproj
- OrrNyan/OrrNyan.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- OrrNyan/OrrNyan/UI/Components/CatButtonStyle.swift
- OrrNyan/OrrNyan/UI/Components/LottieView.swift
- OrrNyan/OrrNyan/UI/Screen/CreateNameView.swift
- added CatButtonStyle
- added LottieView
- PR에 대한 설명
- CreateNameView 생성
- Lottie 재생 기능 추가
- 고양이 이름 저장 버튼 스타일 추가 (CatButtonStyle)
- #12 
- 작업한 내용
- 고양이 이름 생성 시 조건 추가 (CreateNameView)
공백x, 특수문자x, 9글자 이내
- 로티 재생 기능 추가 (LottieView)
- 고양이 이름 저장 버튼 스타일 추가 (CatButtonStyle)
- 참고 사항이 있으면 적어주세요
수정 할 부분이 있다면 알려주세요! (코린이임) 
로티 재생 확인을 위해 임시 고양이 에셋 추가 - fistCat  추가 해두었습니다.
> [FEAT]: #12 - Added CreateNameVIew

- OrrNyan/OrrNyan.xcodeproj/project.pbxproj
- OrrNyan/OrrNyan.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- OrrNyan/OrrNyan/GoogleService-Info.plist
- OrrNyan/OrrNyan/Info.plist
- OrrNyan/OrrNyan/OrrNyan.entitlements
- Firebase 관련 패키지 추가
- feat/#08
- Firebase 관련 패키지 추가
- 구글 로그인 패키지 추가
> [Feat] #08 - add firebase package

- OrrNyan/OrrNyan.xcodeproj/project.pbxproj
- OrrNyan/OrrNyan/OrrNyanApp.swift
- OrrNyan/OrrNyan/UI/Screen/LoginView.swift
- OrrNyan/OrrNyan/Utilities/Firebase/FirebaseManager.swift
- OrrNyan/OrrNyan/Utilities/Firebase/SignInWithApple.swift
- OrrNyan/OrrNyan/Utilities/Firebase/SignInWithGoogle.swift
Firebase 관련 작업 수행
- feat/#08
- Firebase 연동
- Apple Login
- Google Login
> Feat/#08 Firebase

- OrrNyan/OrrNyan/UI/Screen/CreateNameView.swift
- OrrNyan/OrrNyan/UI/Screen/LoginView_malty.swift
-  LoginView -> CreateNameView 합치기
- chore/#39
> [Chore] #39 - LoginView -> CreateNameView 합치기

- OrrNyan/OrrNyan/UI/Screen/Main/MainParallaxView.swift
- PR에 대한 설명
메인뷰에서 element가 프레임 밖에서 안으로 들어오는 애니메이션 구현 부분 코드 수정
- feature/#40
- mainView의 stage01에서 element가 frame 밖에서 안으로 들어오는 애니메이션 코드 수정했습니다. 
|기능|스크린샷|
|:--:|:--:|
|GIF|<img src = "" width ="250">|
> [Refactor] 메인뷰에서 element가 프레임 밖에서 안으로 들어오는 애니메이션 구현 부분 코드 수정했습니다.

- OrrNyan/OrrNyan/OrrNyanApp.swift
- OrrNyan/OrrNyan/UI/Components/ACarousel.swift
- OrrNyan/OrrNyan/ViewModels/ACarouselViewModel.swift
- SVG overlay 완
- feature/#58
- 이제 건물만 클릭해야 스테이지가 선택됩니다.
> Feat/#58 - SVG overlay 완료

- OrrNyan/OrrNyan.xcodeproj/project.pbxproj
- OrrNyan/OrrNyan/Models/User.swift
- OrrNyan/OrrNyan/Models/UserInfo.swift
- OrrNyan/OrrNyan/OrrNyan.entitlements
- OrrNyan/OrrNyan/UI/Screen/LoginView.swift
- OrrNyan/OrrNyan/Utilities/Firebase/FirebaseManager.swift
- OrrNyan/OrrNyan/Utilities/HealthKitManager.swift
- UserInfo, User 모델 변경 
- 헬스킷 추가
- rename/#63
- 모델 변경
- 싱글톤으로 사용할 User 추가
- 헬스킷 코드추가
- 헬스킷, 코어모션 plist 추가
> [Rename] #63 - UserInfo, User 모델 변경, 헬스킷 추가

- OrrNyan/OrrNyan/UI/Screen/MyPageView.swift
> [Feat] #44 - 에러 수정

- OrrNyan/OrrNyan.xcodeproj/project.pbxproj
- OrrNyan/OrrNyan/OrrNyanApp.swift
- OrrNyan/OrrNyan/UI/Screen/CreateNameView.swift
- OrrNyan/OrrNyan/Utilities/DeviceSize.swift
CreateNameView 반응형 작업 및 코드 정리
- feature/#80
CreateNameView 반응형 작업 및 코드 정리
|기능|스크린샷|
|:--:|:--:|
|GIF|<img src = "https://github.com/DeveloperAcademy-POSTECH/mc3-team6-nspu/assets/132278619/a8661061-8c31-4d38-bc50-86c144ced8ec" width ="250">|
> Feat/#80 CreateNameView 반응형 작업 및 코드 정리

- OrrNyan/OrrNyan/UI/Screen/Main/MainTopView.swift
- OrrNyan/OrrNyan/UI/Screen/SantaTestView.swift
- OrrNyan/OrrNyan/UI/Screen/SettingPopupView.swift
SettingPopupView 연결 작업
- feature/#80
SettingPopupView 연결 작업
|기능|스크린샷|
|:--:|:--:|
|GIF|<img src = "https://github.com/DeveloperAcademy-POSTECH/mc3-team6-nspu/assets/132278619/d8aa7284-5ef2-4868-8f09-89245d2b1c20" width ="250">|
> SettingPopupView 연결 작업

- OrrNyan/OrrNyan.xcodeproj/project.pbxproj
- OrrNyan/OrrNyan/UI/Screen/Main/GetHeightModifier.swift
- OrrNyan/OrrNyan/UI/Screen/Main/MainParallaxView.swift
- OrrNyan/OrrNyan/UI/Screen/Main/MainView.swift
- OrrNyan/OrrNyan/UI/Screen/Main/UpCat.swift
MainView 고양이 높이값 이미지 최상단에 무조건 맞추기
- feature/#80
MainView 고양이 높이값 이미지 최상단에 무조건 맞추기
> feat/#80 - MainView 고양이 높이값 이미지 최상단에 무조건 맞추기

- OrrNyan/OrrNyan/UI/Screen/CreateNameView.swift
- OrrNyan/OrrNyan/UI/Screen/Main/MainTopView.swift
- OrrNyan/OrrNyan/UI/Screen/SettingPopupView.swift
- SettingPopupView 호출 시 필요한 코드 추가
- CreateNameView 이름 조건 텍스트 위치 수정
- #85 
- SettingPopupView 호출 시 필요한 코드 추가
MainTopView 
변수 추가 
@Environment(\.scenePhase) private var scenePhase
Sheet에 코드 추가
.environment(\.scenePhase, scenePhase)
- CreateNameView 이름 조건 텍스트 위치 수정
- 코드 수정 필요시 말씀해주세요!
> [Chore] #85 - SettingPopupView의 Scene 전환 감지를 위한 코드 추가

- OrrNyan/OrrNyan/Utilities/Firebase/SignInWithApple.swift
AppleLoin 버그 수정
- fix/#90
- 애플로그인 취소 등의 오류를 throw 해주는 과정에서 발생한 버그를 수정했습니다.
> [Fix] #90 - AppleLoin 버그 수정

- OrrNyan/OrrNyan Watch App/Utilities/StairTest.swift
- OrrNyan/OrrNyan/Models/User.swift
- OrrNyan/OrrNyan/OrrNyanApp.swift
- OrrNyan/OrrNyan/UI/Screen/ContentView.swift
- 현재 층계값을 항상 가지고 있는 User.instance.userFloor 추가
- feat/#93
- User.instance.userFloor 변수로 메인뷰, 스테이지뷰에 떠 있는 층계 값, 마이페이지뷰에서 사용할 수 있게 추가
> [Feat] #93 - 현재 층계값을 항상 가지고 있는 User.instance.userFloor 추가

- OrrNyan/OrrNyan/UI/Screen/MyPage/BadgePopupView.swift
- OrrNyan/OrrNyan/UI/Screen/MyPage/MyPageView.swift
- OrrNyan/OrrNyan/UI/Screen/Stage/StageView.swift
MyPageView 데이터 작업
- feature/#80
MyPageView 데이터 작업
> MyPageView 데이터 작업

- OrrNyan/OrrNyan/UI/Screen/MyPage/BadgePopupView.swift
- OrrNyan/OrrNyan/UI/Screen/MyPage/MyPageView.swift
MyPageView 클릭 시, 데이터 최신화
- feature/#80
MyPageView 클릭 시, 데이터 최신화
> MyPageView 클릭 시, 데이터 최신화

- OrrNyan/OrrNyan/UI/Screen/MyPage/BadgePopupView.swift
- OrrNyan/OrrNyan/UI/Screen/MyPage/MyPageView.swift
MyPageView 데이터 처리
- feature/#80
MyPageView 데이터 처리
> MyPageView 데이터 처리

- OrrNyan/OrrNyan/UI/Screen/Main/MainParallaxView.swift
- PR에 대한 설명
MainParallaxView의 Animation을 보완하였습니다.
- style/#100
- 작업한 내용
1. offset value를 적절한 값으로 조정했습니다.
2. BackOpacityAnimation(), FrameSideAnimation()에 easeInOut animation을 추가했습니다.
- .animation이 구닥다리어서 노란 경고창이 뜹니다,, 문제가 되면 삭제할게요
> style/#100 Parallax Effect 부드럽게 수정

- OrrNyan/OrrNyan/Models/User.swift
- OrrNyan/OrrNyan/Models/UserStage.swift
- OrrNyan/OrrNyan/OrrNyanApp.swift
- OrrNyan/OrrNyan/Utilities/Firebase/FirebaseManager.swift
- Firebase UserStage CRUD 기능 추가
- feat/#99
- Firebase UserStage CRUD 기능 추가
- 앱 실행시 서버에서 받아오게 로직 구현
- 회원가입시 처음 한번만 서버에 create하도록 구현
- 나머지는 업데이트로 처리
> Feat/#99 - Firebase UserStage CRUD

- OrrNyan/OrrNyan.xcodeproj/project.pbxproj
- OrrNyan/OrrNyan/Models/User.swift
- OrrNyan/OrrNyan/OrrNyanApp.swift
- OrrNyan/OrrNyan/UI/Screen/Main/MainTopView.swift
User instance를 environment로 선언 후 사용
user를 가지고 뷰가 감지할 수 있게 변경
- feat/#99
- 작업한 내용
> [Feat] #99 - User instance를 environment로 선언 후 사용

- OrrNyan/OrrNyan.xcodeproj/project.pbxproj
- OrrNyan/OrrNyan/Models/AppFirstLaunch.swift
- OrrNyan/OrrNyan/OrrNyan.entitlements
- OrrNyan/OrrNyan/UI/Screen/Main/MainView.swift
- OrrNyan/OrrNyan/UI/Screen/Stage/ACarousel.swift
- OrrNyan/OrrNyan/ViewModels/ACarouselViewModel.swift
- OrrNyan/OrrNyan/ViewModels/StageViewModel.swift
- MainView, StageView 둘 중 뭐가 나타나야 할지 구현한 PR입니다.
- feature/#106
- 작업한 내용
|기능|스크린샷|
|:--:|:--:|
|GIF|<img src = "" width ="250">|
- 참고 사항이 있으면 적어주세요
> Feat/#106 - MainView, StageView 둘 중 뭐가 나타나야 할지 구현 완료

- OrrNyan/OrrNyan/UI/Components/UserPushNotification.swift
- 알림 내용 변경
- #102 
- 알림 내용 변경
|기능|스크린샷|
- 코드 수정할게 있으면 말씀해주세요~!
> [Chore] #102 - Local Push Alert 내용 수정

- OrrNyan/OrrNyan.xcodeproj/project.pbxproj
- OrrNyan/OrrNyan/OrrNyanApp.swift
- OrrNyan/OrrNyan/UI/Screen/ContentView.swift
- OrrNyan/OrrNyan/UI/Screen/Main/MainTopView.swift
- OrrNyan/OrrNyan/UI/Screen/MyPage/MyPageView.swift
- OrrNyan/OrrNyan/UI/Screen/Stage/StageView.swift
- myPageView 데이터 작업 / NameSpace 원복
- feature/#80
- myPageView 데이터 작업 / NameSpace 원복
> feat/#80 - myPageView 데이터 작업 / NameSpace 원복

- OrrNyan/OrrNyan/OrrNyanApp.swift
- OrrNyan/OrrNyan/Utilities/Firebase/FirebaseManager.swift
로그인시 바로 데이터 받아오는 로직 추가
- feat/#99
- 로그인시 바로 데이터 받아오는 로직 추가
> Feat/#99 로그인시 바로 데이터 받아오는 로직 추가

- OrrNyan/OrrNyan/Models/UserStage.swift
- OrrNyan/OrrNyan/UI/Screen/Stage/ACarousel.swift
- OrrNyan/OrrNyan/UI/Screen/Stage/StageView.swift
- OrrNyan/OrrNyan/ViewModels/ACarouselViewModel.swift
-  버그 수정 및 서버 업데이트 기능 적용
- feature/#110
- 새로워진 userStage를 서버에 업로드합니다.
- 사소한 버그를 수정하였습니다.
- 또다른 버그가 있다면 제보해주세요..
> [FEAT] #110 - 버그 수정 및 서버 업데이트 기능 적용

- OrrNyan/OrrNyan.xcodeproj/project.pbxproj
- OrrNyan/OrrNyan/Models/User.swift
- OrrNyan/OrrNyan/OrrNyan.entitlements
- OrrNyan/OrrNyan/UI/Screen/Alert/FloorUpdatedAlert.swift
- OrrNyan/OrrNyan/UI/Screen/ContentView.swift
- OrrNyan/OrrNyan/UI/Screen/Login/CreateNameView.swift
- OrrNyan/OrrNyan/UI/Screen/Main/MainView.swift
- OrrNyan/OrrNyan/Utilities/Firebase/FirebaseManager.swift
FloorUpdatedAlert 뷰 기능구현, 유저 플로어 로직 일부 수정
- feat/#116
- FloorUpdatedAlert 뷰 기능구현 
- 유저 플로어 로직 일부 수정
- createName뷰 로티 이름 수정
- FloorUpdatedAlert 뷰가 부모 뷰(패럴)에 맞춰져서 사이즈가 안맞는 상황인데.. 머리가 안돌아갑니다. 말티 고쳐줭
> [Feat] #116 - FloorUpdatedAlert 뷰 기능구현, 유저 플로어 로직 일부 수정
